server:
  port: 8769
foo: foo version 1
spring:
  application:
    name: blogger_zuul
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://master:8761/eureka,http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 2

zuul:
  routes:
    api-a:
      path: /api/blogger/**
      serviceId: myclient
