server:
  port: 8050
foo: foo version 1
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://master:8761/eureka,http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 2

spring:
  #  jackson:
  #    date-format: yyyy-MM-dd HH:mm:ss    #或正则yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT+8
  devtools:
    restart:
      enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
  application:
    name: blogger
  main:
    allow-bean-definition-overriding: true
  datasource:
    # 驱动
    # 数据库连接已过时，com.mysql.jdbc.Driver被建议替换为com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    name: blogger
    url: jdbc:mysql://118.31.20.102:3306/my_blogger?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    # 注意修改数据库连接信息
    username: root
    password: Passwd123!
    platform: mysql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    druid:
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
# 配置 MyBatis
mybatis:
  # classpath 在这里代表 src 目录
  mapper-locations: classpath:/mappers/*.xml
  # 全局的映射，不用在xml文件写实体类的全路径
  type-aliases-package: cn.dutyujm.pojo
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true

feign:
  httpclient:
    enabled: true