spring:
  application:
    name: blogger-zuul
  main:
    allow-bean-definition-overriding: true
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
zuul:
  routes:
    api-a:
      path: /api/client/
      serviceId: client