spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: server-one
    instance-id: eureka-8761
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://server-two:8762/eureka/,http://localhost:8763/eureka/
